dokkan_homepage:
    path: /main
    defaults: { _controller: DokkanBundle:Default:index }
    
# Login    
login:
    path: /login
    defaults: { _controller: DokkanBundle:User:login }    
    
login_check:
    path: /login_check
    
logout:
    path: /logout
    
# Login    


#CRUD
#CRUD CATEGORIA
dokkan_index_categoria:
    path: /categories
    defaults: { _controller: DokkanBundle:Categoria:index }

dokkan_add_categoria:
    path: /categories/add
    defaults: { _controller: DokkanBundle:Categoria:add }

dokkan_delete_categoria:
    path: /categories/delete/{id}
    defaults: { _controller: DokkanBundle:Categoria:delete }
    
dokkan_edit_categoria:
    path: /categories/edit/{id}
    defaults: { _controller: DokkanBundle:Categoria:edit }

# CRUD ENTRADA

dokkan_index_entrada:
    path: /entrades
    defaults: { _controller: DokkanBundle:Entrada:index }

dokkan_add_entrada:
    path: /entrades/add
    defaults: { _controller: DokkanBundle:Entrada:add }   
    
dokkan_delete_entrada:
    path: /entrades/delete/{id}
    defaults: { _controller: DokkanBundle:Entrada:delete }
    
dokkan_edit_entrada:
    path: /entrades/edit/{id}
    defaults: { _controller: DokkanBundle:Entrada:edit }

#CRUD