dokkan_homepage:
    path: /
    defaults: { _controller: DokkanBundle:Default:index }
    
# Login    
login:
    path: /login
    defaults: { _controller: DokkanBundle:User:login }    
    
login_check:
    path: /login_check
    
logout:
    path: /logout
    
# Login    

# Registre

register:
    path: /register
    defaults: { _controller: DokkanBundle:User:register } 

# Registre

#CRUD
#CRUD CATEGORIA
dokkan_index_categoria:
    path: /categories
    defaults: { _controller: DokkanBundle:Categoria:index }

dokkan_add_categoria:
    path: /categories/add
    defaults: { _controller: DokkanBundle:Categoria:add }

dokkan_delete_categoria:
    path: /categories/delete/{id}
    defaults: { _controller: DokkanBundle:Categoria:delete }
    
dokkan_edit_categoria:
    path: /categories/edit/{id}
    defaults: { _controller: DokkanBundle:Categoria:edit }

# CRUD ENTRADA

dokkan_index_entrada:
    path: /entrades
    defaults: { _controller: DokkanBundle:Entrada:index }

dokkan_add_entrada:
    path: /entrades/add
    defaults: { _controller: DokkanBundle:Entrada:add }   
    
dokkan_delete_entrada:
    path: /entrades/delete/{id}
    defaults: { _controller: DokkanBundle:Entrada:delete }
    
dokkan_edit_entrada:
    path: /entrades/edit/{id}
    defaults: { _controller: DokkanBundle:Entrada:edit }

#CRUD

# Multi idioma

dokkan_lang:
    path: /entrades/lang/{_locale}
    defaults: { _controller: DokkanBundle:Default:lang }

# Multi idioma

# Comentaris

dokkan_index_comentari:
    path: /comentaris
    defaults: { _controller: DokkanBundle:Comentari:index }

#Editat
dokkan_add_comentari:
    path: /comentaris/add/{id}
    defaults: { _controller: DokkanBundle:Comentari:add }
#Editat

dokkan_delete_comentari:
    path: /comentaris/delete/{id}
    defaults: { _controller: DokkanBundle:Comentari:delete }

dokkan_edit_comentari:
    path: /comentaris/edit/{id}/{id_ent}
    defaults: { _controller: DokkanBundle:Comentari:edit }
    
# Comentaris


# Front-End
dokkan_front_home:
    path: /home
    defaults: { _controller: DokkanBundle:Front:home }

    # Personajes
    
dokkan_front_personajes:
    path: /personajes
    defaults: { _controller: DokkanBundle:Front:personajes }
    
dokkan_front_pj_str:
    path: /personajes/str
    defaults: { _controller: DokkanBundle:Front:pj_str }
    
dokkan_front_pj_agl:
    path: /personajes/agl
    defaults: { _controller: DokkanBundle:Front:pj_agl }
    
dokkan_front_pj_teq:
    path: /personajes/teq
    defaults: { _controller: DokkanBundle:Front:pj_teq }
    
dokkan_front_pj_int:
    path: /personajes/int
    defaults: { _controller: DokkanBundle:Front:pj_int }
    
dokkan_front_pj_phy:
    path: /personajes/phy
    defaults: { _controller: DokkanBundle:Front:pj_phy }
    
dokkan_front_pj_dokkan:
    path: /personajes/dokkan-awaken
    defaults: { _controller: DokkanBundle:Front:pj_dokkan }
    
    # Personajes
    
    # Items
dokkan_front_items:
    path: /items
    defaults: { _controller: DokkanBundle:Front:items }
    
dokkan_front_it_awakening:
    path: /items/awakening-medals
    defaults: { _controller: DokkanBundle:Front:it_awakening }
    
dokkan_front_it_support:
    path: /items/support-items
    defaults: { _controller: DokkanBundle:Front:it_support }
    
dokkan_front_it_training:
    path: /items/training-items
    defaults: { _controller: DokkanBundle:Front:it_training }
    
dokkan_front_it_locations:
    path: /items/training-locations
    defaults: { _controller: DokkanBundle:Front:it_locations }
    # Items
    
dokkan_front_eventos:
    path: /eventos
    defaults: { _controller: DokkanBundle:Front:eventos }
    
dokkan_front_torneos:
    path: /torneos
    defaults: { _controller: DokkanBundle:Front:torneos }

dokkan_front_about:
    path: /about
    defaults: { _controller: DokkanBundle:Front:about }

dokkan_front_contact:
    path: /contact
    defaults: { _controller: DokkanBundle:Front:contact }
       
# Front-End