dokkan_homepage:
    path: /main
    defaults: { _controller: DokkanBundle:Default:index }
login:
    path: /login
    defaults: { _controller: DokkanBundle:User:login }    
    
login_check:
    path: /login_check
    
logout:
    path: /logout