DokkanBundle\Entity\Usuari:
    type: entity
    table: usuaris
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nom:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        email:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        password:
            type: string
            nullable: false
            length: 32
            options:
                fixed: false
        foto:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
                
        role:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
    # Afegit
    oneToMany:
        entrada:
            targetEntity: Entrada
            cascade: [ "persist" ]
            mappedBy: usuari
        comentari:
            targetEntity: Comentari
            cascade: [ "persist" ]
            mappedBy: usuari
    #Afegit
    lifecycleCallbacks: {  }
